# Generated by Django 5.2.7 on 2026-09-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rfq_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfq',
            name='buyer',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='RFQ',
        ),
    ]
